version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: webtempsreel
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app-network

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 5173:5173
    environment:
      NODE_ENV: development
    command: npm run dev
    depends_on:
      - db
    networks:
      - app-network

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/webtempsreel
      JWT_SECRET: secret
      JWT_REFRESH_SECRET: refresh_secret
    command: npm start
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres:

networks:
  app-network:
    driver: bridge